server:
  port: 8082

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: demo-corso
          uri: http://localhost:8080
          predicates:
            - Path=/project-corso/**
          filters:
            - StripPrefix=1

        - id: demo-doc-disc
          uri: http://localhost:8081
          predicates:
            - Path=/project-doc-disc/**
          filters:
            - StripPrefix=1

