server:
  port: 8082

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: Tyson1209
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/**

            - id: corso-service
              uri: http://localhost:8080
              predicates:
                - Path=/corso/**

            - id: docenti-discenti-service
              uri: http://localhost:8081
              predicates:
                - Path=/docenti/**, /discenti/**