  server:
    port: 8082

  spring:
    application:
      name: api-gateway
    datasource:
      url: jdbc:postgresql://localhost:5432/users
      username: postgres
      password: Tyson1209
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    cloud:
      gateway:
        server:
          webmvc:
            routes:
              - id: DOCENTI
                uri: http://localhost:8081
                predicates:
                  - Path=/docenti/**
              - id: DISCENTI
                uri: http://localhost:8081
                predicates:
                  - Path=/discenti/**
              - id: CORSI
                uri: http://localhost:8080
                predicates:
                  - Path=/corsi/**

  jwt:
    secret: mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong
    expiration: 86400000 # 24 ore in millisecondi